### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by CHK-0000** [rhymes-ai/Allegro#19]
Traceback (most recent call last):
  File "C:\Allegro\single_inference.py", line 99, in <module>
    single_inference(args)
  File "C:\Allegro\single_inference.py", line 65, in single_inference
    out_video = allegro_pipeline(
  File "C:\Users\ksl10\anaconda3\envs\test\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Allegro\allegro\pipelines\pipeline_allegro.py", line 773, in __call__
    noise_pred = self.transformer(
  File "C:\Users\ksl10\anaconda3\envs\test\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\ksl10\anaconda3\envs\test\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ksl10\anaconda3\envs\test\lib\site-packages\accelerate\hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Allegro\allegro\models\transformers\transformer_3d_allegro.py", line 331, in forward
    hidden_states = block(
  File "C:\Users\ksl10\anaconda3\envs\test\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\ksl10\anaconda3\envs\test\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ksl10\anaconda3\envs\test\lib\site-packages\accelerate\hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Allegro\allegro\models\transformers\block.py", line 1093, in forward
    attn_output = self.attn1(
  File "C:\Users\ksl10\anaconda3\envs\test\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\ksl10\anaconda3\envs\test\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Allegro\allegro\models\transformers\block.py", line 553, in forward
    return self.processor(
  File "C:\Allegro\allegro\models\transformers\block.py", line 824, in __call__
    hidden_states = F.scaled_dot_product_attention(
RuntimeError: No available kernel. Aborting execution.
___
CUDA 11.8, TORCH 11.8-CU will result in an error.

**Comment by nightsnack** [comment]
Yes. Because you use CUDA 11.8, and we use 12.4.
Not that familiar with cuda and I don't know how to support CUDA 11.8.

**Comment by randaller** [comment]
Getting the same error with CUDA 12.4 on windows.

Commented torch and xformers, installed torch using conda and xformers from facebook's wheel from github artifacts.
```
#torch==2.4.1
#xformers==0.0.28.post1
conda install pytorch==2.4.1 pytorch-cuda=12.4 -c pytorch -c nvidia
```

```
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "D:\Anaconda3\envs\allegro\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:12<00:00,  6.33s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
cpu offload enabled
  0%|                                                                                          | 0/100 [00:00<?, ?it/s]D:\Dev\NN\github\pytorch\Allegro\allegro\models\transformers\block.py:824: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  hidden_states = F.scaled_dot_product_attention(
D:\Dev\NN\github\pytorch\Allegro\allegro\models\transformers\block.py:824: UserWarning: Memory efficient kernel not used because: (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:723.)
  hidden_states = F.scaled_dot_product_attention(
D:\Dev\NN\github\pytorch\Allegro\allegro\models\transformers\block.py:824: UserWarning: Memory Efficient attention has been runtime disabled. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen/native/transformers/sdp_utils_cpp.h:495.)
  hidden_states = F.scaled_dot_product_attention(
D:\Dev\NN\github\pytorch\Allegro\allegro\models\transformers\block.py:824: UserWarning: Flash attention kernel not used because: (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:725.)
  hidden_states = F.scaled_dot_product_attention(
D:\Dev\NN\github\pytorch\Allegro\allegro\models\transformers\block.py:824: UserWarning: CuDNN attention kernel not used because: (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:727.)
  hidden_states = F.scaled_dot_product_attention(
D:\Dev\NN\github\pytorch\Allegro\allegro\models\transformers\block.py:824: UserWarning: The CuDNN backend needs to be enabled by setting the enviornment variable`TORCH_CUDNN_SDPA_ENABLED=1` (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:497.)
  hidden_states = F.scaled_dot_product_attention(
  0%|                                                                                          | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\Dev\NN\github\pytorch\Allegro\single_inference.py", line 99, in <module>
    single_inference(args)
  File "D:\Dev\NN\github\pytorch\Allegro\single_inference.py", line 65, in single_inference
    out_video = allegro_pipeline(
  File "D:\Anaconda3\envs\allegro\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\Dev\NN\github\pytorch\Allegro\allegro\pipelines\pipeline_allegro.py", line 773, in __call__
    noise_pred = self.transformer(
  File "D:\Anaconda3\envs\allegro\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Anaconda3\envs\allegro\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda3\envs\allegro\lib\site-packages\accelerate\hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "D:\Dev\NN\github\pytorch\Allegro\allegro\models\transformers\transformer_3d_allegro.py", line 331, in forward
    hidden_states = block(
  File "D:\Anaconda3\envs\allegro\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Anaconda3\envs\allegro\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda3\envs\allegro\lib\site-packages\accelerate\hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "D:\Dev\NN\github\pytorch\Allegro\allegro\models\transformers\block.py", line 1093, in forward
    attn_output = self.attn1(
  File "D:\Anaconda3\envs\allegro\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Anaconda3\envs\allegro\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Dev\NN\github\pytorch\Allegro\allegro\models\transformers\block.py", line 553, in forward
    return self.processor(
  File "D:\Dev\NN\github\pytorch\Allegro\allegro\models\transformers\block.py", line 824, in __call__
    hidden_states = F.scaled_dot_product_attention(
RuntimeError: No available kernel. Aborting execution.
```
