### ISSUE TITLE
Diffusers out of date. Cannot import name 'cached_download' from 'huggingface_hub'

### ISSUE THREAD

**Issue by ruapotato** [rhymes-ai/Allegro#22]
OS: Debian 12
Install steps:
```
git clone https://github.com/rhymes-ai/Allegro
cd Allegro
python3 -m venv pyevn
source ./pyenv/bin/activate
pip install -r requirements.txt
```
Download via:
```
from huggingface_hub import snapshot_download

# Download the model files
model_path = snapshot_download(
    repo_id="rhymes-ai/Allegro",
    local_dir="./Allegro",  # Local directory to save the model
    revision="main"         # Specify the model version/branch
)
```
But when I run:
```
python single_inference.py \
--user_prompt "Your text description here" \
--save_path ./output_videos/output.mp4 \
--vae path/to/vae \
--dit path/to/transformer \
--text_encoder path/to/text_encoder \
--tokenizer path/to/tokenizer \
--guidance_scale 7.5 \
--num_sampling_steps 100 \
--seed 42
```
I get:
```
Traceback (most recent call last):
  File "/matrix/david/main_home_folder/myProjects/AI/BIN/Allegro/single_inference.py", line 5, in <module>
    from diffusers.schedulers import EulerAncestralDiscreteScheduler
  File "/matrix/david/main_home_folder/myProjects/AI/BIN/Allegro/pyevn/lib/python3.11/site-packages/diffusers/init.py", line 5, in <module>
    from .utils import (
  File "/matrix/david/main_home_folder/myProjects/AI/BIN/Allegro/pyevn/lib/python3.11/site-packages/diffusers/utils/init.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/matrix/david/main_home_folder/myProjects/AI/BIN/Allegro/pyevn/lib/python3.11/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/matrix/david/main_home_folder/myProjects/AI/BIN/Allegro/pyevn/lib/python3.11/site-packages/huggingface_hub/init.py)
```

**Comment by ruapotato** [comment]
The solution is:
```
git clone https://github.com/huggingface/diffusers.git
cd diffusers
pip install -e .
```
This likely needs added to the readme.
